      - name: Detectar y Listar Schemes
        run: |
          xcodebuild -list -project Code.xcodeproj | tee schemes.txt
          # Extrae el primer nombre debajo de "Schemes:"
          FIRST_SCHEME=$(sed -n '/Schemes:/{n;p;}' schemes.txt | xargs)
          echo "SCHEME_NAME=$FIRST_SCHEME" >> $GITHUB_ENV
          echo "El scheme detectado es: $FIRST_SCHEME"

      - name: Compilar App (Sin Firmar)
        run: |
          xcodebuild archive \
            -project Code.xcodeproj \
            -scheme "${{ env.SCHEME_NAME }}" \
            -archivePath CodeApp.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""
